### ISSUE TITLE
Misleading error message on `Option<usize>`

### ISSUE THREAD

**Issue by sffc** [rust-diplomat/diplomat#120]
I had the following code:

```rust
#[diplomat::bridge]
pub mod ffi {
    use alloc::boxed::Box;
    use core::convert::TryFrom;
    use diplomat_runtime::DiplomatResult;
    use icu_segmenter::LineBreakSegmenter;
    use icu_segmenter::LineBreakIterator;

    #[diplomat::opaque]
    /// An ICU4X line-break segmenter, capable of finding breakpoints in strings.
    /// See [the Rust docs](https://unicode-org.github.io/icu4x-docs/doc/icu_segmenter/struct.LineBreakSegmenter.html) for more information.
    pub struct ICU4XLineBreakSegmenter(LineBreakSegmenter);

    #[diplomat::opaque]
    pub struct ICU4XLineBreakIterator<'a, 'b>(LineBreakIterator<'a, 'b, char>);

    impl ICU4XLineBreakSegmenter {
        /// Construct an [`ICU4XLineBreakSegmenter`] from an locale identifier.
        /// See [the Rust docs](https://unicode-org.github.io/icu4x-docs/doc/icu_segmenter/struct.LineBreakSegmenter.html#method.from_bytes) for more information.
        pub fn try_new() -> DiplomatResult<Box<ICU4XLineBreakSegmenter>, ()> {
            LineBreakSegmenter::try_new()
                .map(|o| Box::new(ICU4XLineBreakSegmenter(o)))
                .map_err(|_| ())
                .into()
        }

        pub fn segment_str<'a, 'b>(&'a self, input: &'b str) -> Box<ICU4XLineBreakIterator<'a, 'b>> {
            Box::new(ICU4XLineBreakIterator(self.0.segment_str(input)))
        }
    }

    impl<'a, 'b> ICU4XLineBreakIterator<'a, 'b> {
        pub fn next(&mut self) -> Option<usize> {
            self.0.next()
        }
    }
}
```

When I built this code, I got:

```
thread 'main' panicked at 'not yet implemented', tool/src/c/types.rs:45:18
stack backtrace:
   0:     0x55eaf30a0b9c - std::backtrace_rs::backtrace::libunwind::trace::hd3a6cb8e32f9fc43
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
...
  15:     0x55eaf2e35f6d - core::panicking::panic::h36a242770663c3a8
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:50:5
  16:     0x55eaf2e6abb8 - diplomat_tool::c::types::gen_type::hfe47e92f72599f63
  17:     0x55eaf2e74d22 - diplomat_tool::c::structs::gen_method::hbb55954fde7bc795
  18:     0x55eaf2e4c913 - diplomat_tool::c::gen_bindings::hddcd509b22ecc62e
  19:     0x55eaf2e538d7 - diplomat_tool::main::h14053dfa261ba459
  20:     0x55eaf2e5b4c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4de5a6aa9c817b9e
...
```

I had to go to `tool/src/c/types.rs:45:18` at the correct Git revision in order to find out that it was hitting this line:

```rust
            _ => unreachable!("Cannot have non-pointer types inside Option"),
```

Two problems:

1. This code is clearly not `unreachable`
2. This should be changed to produce a more helpful error message. I don't know why the string inside the `unreachable!()` doesn't make it into the error output.

**Comment by Manishearth** [comment]
So it's the job of one of the validity checks to ensure the code never reaches there: check_validity is failing here, I don't know why

**Comment by Manishearth** [comment]
Wait, is this in icu4x? It's not updated to the latest diplomat, icu4x's diplomat version (a) does not have the appropriate diagnostic and (b) has a `todo!()` instead of an `unreachable!()` which explains the misleading diagnostic

**Comment by sffc** [comment]
ICU4X diplomat is b448e1e272b70eae1cb2e6b7d0a2f0c68905d49a which I misread as being the latest Diplomat, but it is actually the parent of the latest diplomat.  And the latest commit did a bunch of stuff with `Option`, so it makes sense that this is probably fixed.
