### ISSUE TITLE
Can't use structs from other modules without importing all field types

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#248]
```rust
// foo.rs
#[diplomat::bridge]
mod ffi {
    pub enum UnimportedEnum {
        A,
        B,
        C
    }


    pub struct ImportedStruct {
        foo: UnimportedEnum,
        int: u8,
    }   
}

//bar.rs
#[diplomat::bridge]
mod ffi {
   use crate::foo::ffi::ImportedStruct;


   #[diplomat::opaque]
   pub struct Opaque;


   impl Opaque {
      pub fn returns_imported() -> ImportedStruct {
           unimplemented()
      }
   }
}
```

This fails with:

```
thread 'main' panicked at 'Could not resolve symbol UnimportedEnum in bar::ffi', core/src/ast/types.rs:229:29
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: diplomat_core::ast::types::PathType::resolve_with_path
             at /home/manishearth/dev/diplomat/core/src/ast/types.rs:229:29
   3: diplomat_core::ast::types::PathType::resolve
             at /home/manishearth/dev/diplomat/core/src/ast/types.rs:245:9
   4: diplomat_tool::js::Imports::collect_usages
             at /home/manishearth/dev/diplomat/tool/src/js/mod.rs:216:30
   5: diplomat_tool::js::Imports::collect_usages
             at /home/manishearth/dev/diplomat/tool/src/js/mod.rs:237:29
   6: diplomat_tool::js::Imports::new
             at /home/manishearth/dev/diplomat/tool/src/js/mod.rs:189:17
   7: diplomat_tool::js::gen_bindings
             at /home/manishearth/dev/diplomat/tool/src/js/mod.rs:62:23

```

during JS generation (also docs generation, IIRC)

and can be fixed by importing `UnimportedEnum` into bar.rs. This should be unnecessary.

I think the resolution algorithm is not resolving struct fields in their source context.

**Comment by Manishearth** [comment]
I think this would basically be solved "by free" by HIR, the AST doesn't do resolution this way and it's annoying to shoehorn the right resolution in.
