### ISSUE TITLE
How to use DiplomateByte at this point?

### ISSUE THREAD

**Issue by irvingoujAtDevolution** [rust-diplomat/diplomat#443]
I tried to use the latest commit as my dependency like this 
```
[dependencies]
diplomat = {git = "https://github.com/rust-diplomat/diplomat.git", rev = "c7bea72852e6f0f5df3800bf882222fa4697fcfc"}
diplomat-runtime = {git = "https://github.com/rust-diplomat/diplomat.git", rev = "c7bea72852e6f0f5df3800bf882222fa4697fcfc"}
```

and I update diplomate-tool to latest, I try to write some code like this 
```
  pub fn get_buffer(&self, buf: &DiplomatByte){
            todo!()
        }
```

but I get 

```
PS C:\Users\jou\code\IronRDP\ffi> diplomat-tool c ./c
thread 'main' panicked at C:\Users\jou\.cargo\registry\src\index.crates.io-6f17d22bba15001f\diplomat_core-0.7.0\src\ast\types.rs:242:29:
Could not resolve symbol DiplomatByte in session::ffi
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Cargo check works fine. and if I do this
```
      pub fn get_buffer(&self, buf: &diplomat_runtime::DiplomatByte){
            todo!()
        }

```

I got 
```
PS C:\Users\jou\code\IronRDP\ffi> diplomat-tool c ./c
thread 'main' panicked at C:\Users\jou\.cargo\registry\src\index.crates.io-6f17d22bba15001f\diplomat_core-0.7.0\src\ast\types.rs:242:29:
Could not resolve symbol diplomat_runtime in session::ffi
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by robertbastian** [comment]
&DiplomatByte is not supported, only &[DiplomatByte]. If you're trying to pass a buffer, you need to use a slice.

**Comment by irvingoujAtDevolution** [comment]
Looks like slice is not yet supported in C#?

**Comment by Manishearth** [comment]
Yeah the c# backend was contributed by a third party and is not actively maintained by the diplomat team, we accept patches and add feature support when it's easy to do so.

**Comment by CBenoit** [comment]
@irvingoujAtDevolution I suggest closing this "question" issue (answered above), and opening a new issue for tracking the support of `&[DiplomatByte]` in the C# backend instead.
